@startuml
!include ../skin.puml
!include ../variables.puml

'' Montrer peut etre l'ordre des différentes activités : (workflow de l'agent) ???
'' d'abord mettre les congés et formations puis indiquer les horaires de guichet
'' puis le reste

title Diagramme d'activité du CU 5\n----

note left: ACTEUR_AGENT
(*) --> "ConsulterAgenda"
note left: Il peut s'agir de \nl'agenda quotidien\n ou hebdomadaire (defaut)
--> "ModePlanification"
--> "SelectPlage"
--> "SelectActivite"
--> "CreerPlage"
--> "MajNbContacts"
--> "ModePlanification"
--> "SortirPlanification"
--> (*)

@enduml