@startuml
!include ../skin.puml
!include ../variables.puml

title Diagramme d'activité du CU 5\n----

note left: ACTEUR_CHEF_AG
(*) --> "ListeAgents"
"ListeAgents" --> "SelectAgent"
"SelectAgent" --> "ListePlages"
"ListePlages" --> "SelectPlage"
"SelectPlage" --> "ListeActivites"
"ListeActivites" --> "SelectActivite"

if "encore des activités\nà plannifier"
    --> [oui] "ListePlages"
else
    --> "MajNbContacts"
endif
"MajNbContacts" --> (*)

@enduml