@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme de Séquence Détaillé du CU 5\n----

actor "ACTEUR_CHEF"

"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_ConsulterAgenda
"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_ModePlanification
alt ajouter une plage
	"ACTEUR_CHEF" -> "ACTEUR_IHM" : SAISIE_SelectPlage
	"ACTEUR_CHEF" -> "ACTEUR_IHM" : SAISIE_SelectActivite
	"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_CreerPlage
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_CreerPlageAgenda
	"ACTEUR_SI" -> Agenda : SOM_CreerPlageAgenda

else terminer la planification
	"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_SortirPlanification
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_MettreAJourNbContactsPotentiels
	"ACTEUR_SI" -> Agenda : SOM_ObtenirTempsPourRdv
	Agenda -> Structure : SOM_MettreAJourNbContactsPotentiels
end

@enduml