@startuml
!include ../skin.puml
!include ../variables.puml
title DSS du CU 5\n----

actor "ACTEUR_USER"

"ACTEUR_USER" -> "ACTEUR_IHM" : ConsulterAgenda
note right: TODO -> Dans le CU 7 retourner la liste des activités
"ACTEUR_USER" -> "ACTEUR_IHM" : ModePlanification
alt ajouter une plage
	"ACTEUR_USER" -> "ACTEUR_IHM" : SelectPlage
	"ACTEUR_USER" -> "ACTEUR_IHM" : SelectActivite
	"ACTEUR_USER" -> "ACTEUR_IHM" : CreerPlage
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_CreerPlageAgenda
else terminer la planification
	"ACTEUR_USER" -> "ACTEUR_IHM" : SortirPlanification
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_MettreAJourNbContactsPotentiels
end

@enduml