@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 3\n----

note left: ACTEUR_CHEF_AG
(*) --> LB_ListeAgents
--> LB_DetailAgent
--> LB_ContactsAgent
--> LB_DetailContact
-->(*)

@enduml