@startuml
!include ../skin.puml
!include ../variables.puml

title Diagramme de séquence détaillé du CU 3\n----

actor ACTEUR_USER

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ListeAgents
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirAgents (CU 2)

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerAgent
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailAgent
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirAgent
"ACTEUR_SI" -> Structure : SOM_ObtenirAgent
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirContactsAgent
"ACTEUR_SI" -> Contact : SOM_ObtenirContactsAgent
loop Pour chaque contact
	Contact -> Structure : SOM_ObtenirAgent
	Contact -> Agenda : SOM_ObtenirPlageAgenda
	Contact -> Client : SOM_ObtenirClient
end

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerContact
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_Ref_DetailContact


@enduml