@startuml
!include ../skin.puml
!include ../variables.puml

title Diagramme de séquence système du CU 3\n----

actor ACTEUR_USER

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ListeAgents (CU 2)

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerAgent
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailAgent
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirContactsAgent

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerContact
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_Ref_DetailContact

@enduml