@startuml
!include ../skin.puml
title Diagramme d'activité CU 10\n Consulation du dossier client\n----


start
:Liste contacts prévus de l'agent;
split
:Consulter bilant client\n(Cotation, bilan,\nliste de personnes);
split
:Consulter details\nd'une personne;
:Maj personne;
split again
:Ajouter une personne;
if(Personne existante ?) then(oui)
else (non)
:Créer nouvelle personne;
endif
split again
:Supprimer une personne;
stop
end split
split again
:Consulter produits du\nclient à la banque\net à la concurrence;
split
:Consulter détails\nd'un compte;
split again
:Consulter détail\n d'un produit;
split again
:Maj compte/produit\nà la concurrence;
end split
split again
:Maj entête client;
stop
split again
:Consulter relations\n banque-client;
stop
end split

stop
@enduml