@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité\ndu CU 9\n----

note left: ACTEUR_AGENT
(*) --> "LB_IdentifierContact"
--> "LB_DetailsContact"
if "Preparation faite ?" then
  -->[oui]"LB_AfficherPreparation"
  --> "LB_DossierClient"
else
  -->[non]"LB_DossierClient"
endif
--> ===B1===
--> "LB_ListerOffres"
--> "LB_DetailsDesOffresCatalogue"
--> ===B2===
===B1=== --> "LB_RedigerEtSoumettrePropositions"
--> ===B2===
--> "LB_EnregistrerRapportActiviteCommerciale"
note right: NoteContactTermine
--> (*)
@enduml