@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité\ndu CU 9\n----

(*) --> "IdentifierContact"
if "Preparation faite ?" then
  -->[oui]"AfficherPreparation"
  --> "ConsulterDossierClient"
else
  -->[non]"ConsulterDossierClient"
endif
--> "EnregistrerRapportActiviteCommerciale"
--> (*)
@enduml