@startuml
!include ../skin.puml
!include ../variables.puml

title Diagramme de séquence système du CU 9\n----

actor "ACTEUR_USER"

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_EntrerInfosContact
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_IdentifierContact (CU 8)

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailContact (CU 4)

alt Préparation faite
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_AfficherPreparation
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirPropositionCommerciale
end

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerClient
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDossierClient (CU 8)

par
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ListerOffres (CU 8)
	
	"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerOffre
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailsDesOffresCatalogue (CU 8)
else
	"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_RedigerProposition
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_CreerPropositionOffre (CU 8)
end

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_EnregistrerRapportActiviteCommerciale
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_EnregistrerRapportActivite

@enduml