@startuml
!include ../skin.puml
title Diagramme d'activité du CU 4\n----


(*) --> "Consulter liste des contacts prévus de l'agence" as ListeContactsPrevus
ListeContactsPrevus-->[si même client] "Regrouper contacts" as RegrouperContacts
RegrouperContacts--> (*)
ListeContactsPrevus--> "Consulter détails contact" as DetailContact
DetailContact--> "Enregistrer raison annulation" as RaisonAnnulation
RaisonAnnulation--> "Annuler contact" as AnnulerContact
DetailContact--> "Prendre RDV" as PrendreRDV
DetailContact--> "Preparer RDV" as PreparerRDV
DetailContact--> "Conduire RDV" as ConduireRDV
AnnulerContact--> (*)
PrendreRDV--> (*)
PreparerRDV--> (*)
ConduireRDV--> (*)

@enduml