@startuml
!include ../skin.puml
!include ../variables.puml
title DSS du CU 4\n----

actor "ACTEUR_USER"

"ACTEUR_USER" -> "ACTEUR_IHM" : ListeContactsATraiter
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirContactsAffectes
alt même client
	"ACTEUR_USER" -> "ACTEUR_IHM" : GrouperContacts
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_GrouperContacts
else clients différents
	"ACTEUR_USER" -> "ACTEUR_IHM" : DetailContact
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailsContact
	alt annulation contact
		"ACTEUR_USER" -> "ACTEUR_IHM" : AnnulerContact
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_AnnulerContact
		"ACTEUR_USER" -> "ACTEUR_IHM" : RaisonAnnulation
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_EnregistrerMotifAnnulation
	else prise RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : PrendreRDV
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_PrendreRdv
	else preparation RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : PreparerRDV
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_PreparerRdv
	else conduire RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : ConduireRDV
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConduireRdv
	end
end

@enduml