@startuml
!include ../skin.puml
!include ../variables.puml

title Identifier le client\n----

start
:LB_IdentifierClient;
note left: ACTEUR_AGENT\nVoir DA Identifier Client
split
:LB_ConsulterBilanClient;
split
:LB_ConsulterDetailsPersonne;
:LB_MAJPersonne;
split again
:Ajouter une personne;
if(Personne existante ?) then(oui)
else (non)
:LB_CreerNouvellePersonne;
endif
split again
:Supprimer une personne;
stop
end split
split again
:LB_ConsulerProduitsClient;
split
:LB_ConsulterDetailsCompte;
split again
:LB_ConsulterDetailsProduit;
split again
:LB_MAJCompteConcurrence;
end split
split again
:LB_MAJCompteEnteteClient;
stop
split again
:LB_ConsulterRelationBanqueClient;
:LB_IdentifierContact (CU 8);
note right: NOTE_ClicEvtRdvProp
stop
end split
stop
@enduml