@startuml
!include ../skin.puml
!include ../variables.puml

title Identifier le client\n----

start
:IdentifierClient;
note left: ACTEUR_AGENT\nVoir DA Identifier Client
split
:ConsulterBilanClient;
split
:ConsulterDetailsPersonne;
:MAJPersonne;
split again
:Ajouter une personne;
if(Personne existante ?) then(oui)
else (non)
:CreerNouvellePersonne;
endif
split again
:Supprimer une personne;
stop
end split
split again
:ConsulerProduitsClient;
split
:ConsulterDetailsCompte;
split again
:ConsulterDetailsProduit;
split again
:MAJCompteConcurrence;
end split
split again
:MAJCompteEnteteClient;
stop
split again
:ConsulterRelationBanqueClient;
stop
end split
stop
@enduml