@startuml
!include ../skin.puml
!include ../variables.puml

!define SM_ObtenirClientEtAgence ObtenirClientEtAgence(idClient)\n: Client, Agence
!define SOM_ObtenirAgenceDuClient ObtenirAgenceDuClient(idClient)\n: Agence
!define SOM_ObtenirDetailsPersonne ObtenirDetailsPersonne(idPersonne)\n: adresse, revenu, impot, dateNaissance
!define SOM_ObtenirClientsDeLaPersonne ObtenirClientsPersonne(idPersonne)\n: Liste<Client>
!define SOM_ObtenirDetailsProduit ObtenirDetailsProduit(idProduit)\n: solde, découvert, interet...
title DSD - CU 10\n----

Actor "ACTEUR_USER"
ref over "ACTEUR_USER", "ACTEUR_IHM"  : LB_IdentifierClient
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDossierClient
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirClientEtAgence
"ACTEUR_SI" -> Client : SOM_ObtenirClient
"ACTEUR_SI" -> Structure : SOM_ObtenirAgenceDuClient


opt Bilan
    "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterBilanClient
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConsulterBilanClient
    "ACTEUR_SI" -> Client : SOM_ConsulterBilanClient
	loop Pour chaque personne
		Client -> Personne : SOM_ObtenirPersonne
	end
	
    opt
        "ACTEUR_USER" -> "ACTEUR_IHM" : Sélectionner Personne
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDetailsPersonne
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConsulterDetailsPersonne
        "ACTEUR_SI" -> Personne : SOM_ObtenirDetailsPersonne
		"ACTEUR_SI" -> Client : SOM_ObtenirClientsDeLaPersonne

        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_MAJPersonne
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_MAJPersonne
        "ACTEUR_SI" -> Personne : SOM_MAJPersonne
    else
        "ACTEUR_USER" -> "ACTEUR_IHM" : Saisir Informations
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_RecupererPersonne
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_RecupererPersonne
        "ACTEUR_SI" -> Personne : SOM_TrouverPersonne

        opt
            "ACTEUR_USER" -> "ACTEUR_IHM" : LB_AjouterPersonne
            "ACTEUR_IHM" -> "ACTEUR_SI" : SM_AjouterPersonne
            "ACTEUR_SI" -> Client : SOM_AjouterPersonne
        else
            "ACTEUR_USER" -> "ACTEUR_IHM" : LB_CreerNouvellePersonne
            "ACTEUR_IHM" -> "ACTEUR_SI" : SM_CreerEtAjouterNouvellePersonne
            "ACTEUR_SI" -> Personne : SOM_CreerPersonne
			"Personne" -> Client : SOM_AjouterPersonne
        end
    else
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_SupprPersonne
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_SupprimerPersonne
        "ACTEUR_SI" -> Client : SOM_SupprimerPersonne
    end
else
    "ACTEUR_USER" -> "ACTEUR_IHM" : Saisir Nouvelle Entete
    "ACTEUR_USER" -> "ACTEUR_IHM" : LB_MAJCompteEnteteClient
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_MAJEnteteDossier
    "ACTEUR_SI" -> Client : SOM_MajEnteteDossier
end

opt Produits
    "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulerProduitsClient
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirProduits
    "ACTEUR_SI" -> Client : SOM_ObtenirProduits
	loop Pour chaque produit
		Client -> Produit : SOM_ObtenirProduit
	end

    opt Details compte
        "ACTEUR_USER" -> "ACTEUR_IHM" : Sélectionner Compte
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDetailsCompte
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailCompte
        "ACTEUR_SI" -> "Client" : SOM_ObtenirCompte
    end

    opt Détail Produit / Sélectionner Produit
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDetailsProduit
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailProduit
        "ACTEUR_SI" -> "Produit" : SOM_ObtenirDetailsProduit
    end

    opt Mise à jour compte
        "ACTEUR_USER" -> "ACTEUR_IHM" : Saisir Informations
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_MAJCompteConcurrence
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_MAJComptesConcurrence
        "ACTEUR_SI" -> Client : SOM_MAJComptesConcurrence
    end

end

opt Relations banque/client
    "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterRelationBanqueClient
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConsulterRelationsBanqueClient
    "ACTEUR_SI" -> Client : SOM_ConsulterInfosRelationClient
    "ACTEUR_SI" -> Contact : SOM_ConsulterPropositionsHistorique
    "ACTEUR_SI" -> Evenement : SOM_ConsulterEvenementsAVenir
end

@enduml