@startuml
!include ../skin.puml
!include ../variables.puml
title DSS - CU 10\n----

Actor "ACTEUR_USER"
ref over "ACTEUR_USER", "ACTEUR_IHM"  : LB_IdentifierClient
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDossierClient
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConsulterDossierClient
opt Bilan
    "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterBilanClient
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConsulterBilanClient
    opt
        "ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerPersonne
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDetailsPersonne
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConsulterDetailsPersonne
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_MAJPersonne
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_MAJPersonne
    else
        "ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SaisirInfosPersonne
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_RecupererPersonne
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_RecupererPersonne
        opt
            "ACTEUR_USER" -> "ACTEUR_IHM" : LB_AjouterPersonne
            "ACTEUR_IHM" -> "ACTEUR_SI" : SM_AjouterPersonne
        else
            "ACTEUR_USER" -> "ACTEUR_IHM" : LB_CreerNouvellePersonne
            "ACTEUR_IHM" -> "ACTEUR_SI" : SM_CreerEtAjouterNouvellePersonne
        end
    else
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_SupprPersonne
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_SupprimerPersonne
    end
else
    "ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_EnteteDossier
    "ACTEUR_USER" -> "ACTEUR_IHM" : LB_MAJCompteEnteteClient
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_MAJEnteteDossier
end

opt Produits
    "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulerProduitsClient
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirProduits
    opt Details compte
        "ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerCompte
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDetailsCompte
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailCompte
    end
    opt Détail Produit / Sélectionner Produit
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDetailsProduit
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailProduit
    end
    opt Mise à jour compte
        "ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SaisirInfosCompte
        "ACTEUR_USER" -> "ACTEUR_IHM" : LB_MAJCompteConcurrence
        "ACTEUR_IHM" -> "ACTEUR_SI" : SM_MAJComptesConcurrence
    end
end

opt Relations banque/client
    "ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterRelationBanqueClient
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConsulterRelationsBanqueClient
end


@enduml