@startuml
!include ../skin.puml
title Diagramme de séquence système du CU 2\n----

actor User

User -> IHM : Consulter liste des contacts prévus de son agence
IHM -> Système : ObtenirContactsPrevus(idStructure) \n: Liste <Contact>
User -> IHM : Consulter détails contact
IHM -> Système : ObtenirDetailsContact(idContact) \n: Details
User -> IHM : Consulter dossier client
IHM -> Système : ObtenirDossierClient(idClient) : Client
User -> IHM : Consulter liste des agents de son agence
IHM -> Système : ObtenirAgents(idAgence) \n: Liste<Agent>
User -> IHM : Consulter détails agent
IHM -> Système : ObtenirDetailsAgent(idAgent) \n: Details
User -> IHM : Affecter le contact à cet agent
IHM -> Système : AffecterContact(idContact, idAgent)
IHM -> Système : MettreAJourIndicateursAgent(idAgent)


@enduml