@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 4\n----

note left: ACTEUR_AGENT
(*) --> "ListeContactsATraiter"
--> "RegrouperContacts"
note top: NoteRegroupementContacts
--> (*)
"ListeContactsATraiter"--> "DetailContact"
"DetailContact" --> "AnnulerContact"
"AnnulerContact" --> "RaisonAnnulation"
"DetailContact"--> "PrendreRDV"
"DetailContact" --> "PreparerRDV"
"DetailContact" --> "ConduireRDV"
"RaisonAnnulation" --> (*)
"PrendreRDV" --> (*)
"PreparerRDV" --> (*)
"ConduireRDV" --> (*)
@enduml