@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 4\n----

note left: ACTEUR_AGENT
(*) --> "LB_ListeContactsATraiter"
--> "LB_RegrouperContacts"
note top: NOTE_RegroupementContacts
--> (*)
"LB_ListeContactsATraiter"--> "LB_DetailContact"
"LB_DetailContact" --> "LB_AnnulerContact"
"LB_AnnulerContact" --> "LB_RaisonAnnulation"
"LB_DetailContact"--> "LB_PrendreRDV"
"LB_DetailContact" --> "LB_PreparerRDV"
"LB_DetailContact" --> "LB_ConduireRDV"
"LB_RaisonAnnulation" --> (*)
"LB_PrendreRDV" --> (*)
"LB_PreparerRDV" --> (*)
"LB_ConduireRDV" --> (*)
@enduml