@startuml
!include ../skin.puml
!include ../variables.puml

title Diagramme de séquence détaillé du CU 4\n----

actor "ACTEUR_USER"

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ListeContactsATraiter
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirAgent (CU 3)

"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirContactsAffectes
"ACTEUR_SI" -> Contact : SOM_ObtenirContactsAffectes
loop Pour chaque contact
	Contact -> Structure : SOM_ObtenirAgent
	Contact -> Agenda : SOM_ObtenirPlageAgenda
	Contact -> Client : SOM_ObtenirClient
end

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerContact
alt sélection d'autres contacts d'un même client
    "ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerContacts
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_RegrouperContacts
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_GrouperContacts
	"ACTEUR_SI" -> Contact : SOM_GrouperContacts
else sélection d'un seul contact

	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailContact
    ''note : plusieurs agents
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailsContact
    "ACTEUR_SI" -> Contact : SOM_ObtenirDetailsContact
    Contact -> Client : SOM_ObtenirClient
    Contact -> Structure : SOM_ObtenirAgent
    Contact -> Produit : SOM_DetailOffre

	alt annulation contact
		"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_MotifAnnulation
		
		"ACTEUR_USER" -> "ACTEUR_IHM" : LB_AnnulerContact
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_AnnulerContact
		"ACTEUR_SI" -> Contact : SOM_AnnulerContact
		"ACTEUR_SI" -> Agenda : SOM_AnnulerContact

	else prise RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : LB_PrendreRDV
	else preparation RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : LB_PreparerRDV
	else conduire RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConduireRDV
	end
end

@enduml