@startuml
!include ../skin.puml
!include ../variables.puml

title Diagramme de séquence détaillé du CU 4\n----

actor "ACTEUR_USER"

"ACTEUR_USER" -> "ACTEUR_IHM" : ListeContactsATraiter
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirContactsAffecte
"ACTEUR_SI" -> Structure : SOM_ObtenirContactsAffectes
alt même client
	"ACTEUR_USER" -> "ACTEUR_IHM" : RegrouperContacts
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_GrouperContacts
	"ACTEUR_SI" -> Client : SOM_GrouperContacts
else clients différents
	"ACTEUR_USER" -> "ACTEUR_IHM" : DetailContact
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailsContact
	"ACTEUR_SI" -> Contact : SOM_ObtenirDetailsContact
	alt annulation contact
		"ACTEUR_USER" -> "ACTEUR_IHM" : AnnulerContact
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_AnnulerContact
		"ACTEUR_SI" -> Client : SOM_AnnulerContact
		"ACTEUR_USER" -> "ACTEUR_IHM" : RaisonAnnulation
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_EnregistrerMotifAnnulation
		"ACTEUR_SI" -> "ACTEUR_SI" : SOM_EnregistrerMotifAnnulation
	else prise RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : PrendreRDV
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_PrendreRdv
		"ACTEUR_SI" -> Contact : SOM_PrendreRdv
	else preparation RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : PreparerRDV
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_PreparerRdv
		"ACTEUR_SI" -> Contact : SOM_PreparerRdv
	else conduire RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : ConduireRDV
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ConduireRdv
		"ACTEUR_SI" -> Contact : SOM_ConduireRdv
	end
end

@enduml