@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme de Séquence Système du CU 4\n----

actor "ACTEUR_USER"

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ListeContactsATraiter

"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirContactsAffectes

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerContact
alt sélection d'autres contacts d'un même client
    "ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerContacts
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_RegrouperContacts
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_GrouperContacts
else sélection d'un seul contact

	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailContact
    ''note : plusieurs agents
    "ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailsContact

	alt annulation contact
		"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_MotifAnnulation
		
		"ACTEUR_USER" -> "ACTEUR_IHM" : LB_AnnulerContact
		"ACTEUR_IHM" -> "ACTEUR_SI" : SM_AnnulerContact

	else prise RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : LB_PrendreRDV
	else preparation RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : LB_PreparerRDV
	else conduire RDV
		"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConduireRDV
	end
end

@enduml