@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 7\n----

note left: ACTEUR_AGENT
(*) --> "ConsulterAgendaHebdomadaire"
"ConsulterAgendaQuotidien" --> "ChangerDate"
"ChangerDate" --> "ConsulterAgendaQuotidien"
"ConsulterAgendaQuotidien" --> "VoirDetailsRDV"
"ConsulterAgendaQuotidien" --> "ModifierPlageHoraire"
"ConsulterAgendaQuotidien" --> "AnnulerRDV"
"ConsulterAgendaQuotidien" --> "ReaffecterRDV"
"ChangerAgent" --> "ConsulterAgendaHebdomadaire"
note left: Par défaut, l'agent connecté
"ConsulterAgendaHebdomadaire" --> "ChangerAgent"
"ConsulterAgendaHebdomadaire" --> "ChangerSemaine"
"ChangerSemaine" --> "ConsulterAgendaHebdomadaire"
"ConsulterAgendaHebdomadaire" --> "VoirDetailsRDV"
"ConsulterAgendaHebdomadaire" --> "ModifierPlageHoraire"
"ConsulterAgendaHebdomadaire" --> "AnnulerRDV"
"ConsulterAgendaHebdomadaire" --> "ReaffecterRDV"
"ConsulterAgendaHebdomadaire" --> "ConsulterAgendaQuotidien"
"ConsulterAgendaQuotidien" --> "ConsulterAgendaHebdomadaire"
"VoirDetailsRDV" --> (*)
"ModifierPlageHoraire" --> (*)
"AnnulerRDV" --> (*)
"ReaffecterRDV" --> (*)

@enduml