@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 2\n----

note left: ACTEUR_CHEF_AG
(*) --> LB_ListeContacts
--> LB_DetailContact
--> LB_DossierClient
--> LB_ListeAgents
--> LB_DetailAgent
--> LB_AffecterAgent
note left: NoteIncContact
--> (*)

@enduml