@startuml
!include ../skin.puml
!include ../variables.puml


title Diagramme de séquence détaillé du CU 2\n----

actor "ACTEUR_CHEF"

"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_ListeContacts
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirContactsPrevus
"ACTEUR_SI" -> Contact : SOM_ObtenirContactsAgence
loop Pour chaque contact
	Contact -> Structure : SOM_ObtenirAgent
	Contact -> Agenda : SOM_ObtenirPlageAgenda
	Contact -> Client : SOM_ObtenirClient
end

"ACTEUR_CHEF" -> "ACTEUR_IHM" : SAISIE_SelectionnerContact

"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_Ref_DetailContact

"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_DossierClient
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirClientContact
"ACTEUR_SI" -> Client : SOM_ObtenirClientContact

"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_ListeAgents
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirAgents
"ACTEUR_SI" -> Structure : SOM_ObtenirAgentsStructure

"ACTEUR_CHEF" -> "ACTEUR_IHM" : SAISIE_SelectionnerAgent

"ACTEUR_CHEF" -> "ACTEUR_IHM" : LB_AffecterAgent
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_AffecterContact
"ACTEUR_SI" -> Contact : SOM_AffecterContact
"ACTEUR_SI" -> Structure : SOM_MettreAJourNbContactsAffectes


@enduml