@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme de séquence système du CU 2\n----

actor "ACTEUR_USER"

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ListeContacts
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirContactsPrevus
"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerContact
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailContact
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailsContact
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DossierClient
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ListeAgents
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirAgents
"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerAgent
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailAgent
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailsAgent
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_AffecterAgent
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_AffecterContact

@enduml