@startuml
!include ../skin.puml
title Diagramme d'état de \nl'Object Métier Contact\n----

[*] -> PREVU : [CU1] : génération\npar le système

state "EN TRAITEMENT" as EnTraitement {

state "RDV PRIS" as RdvPris

[*] --> RdvPris : [CU6] : contact spontané

PREVU -> AFFECTE : [CU2] : affectation\npar le chef d'agence

AFFECTE --> RdvPris : [CU6] : rendez-vous pris\npar l'agent

RdvPris --> PREPARE : [CU8] : préparation\npar l'agent

RdvPris --> AFFECTE : [CU7] : annulation du rendez-vous\npar l'agent
PREPARE --> PREPARE : [CU7] : annulation du rendez-vous\npar l'agent

}

RdvPris --> REALISE : [CU9] : conduite de l'entretien\npar l'agent
PREPARE --> REALISE : [CU9] : conduite de l'entretien\npar l'agent

EnTraitement --> ANNULE : [CU4] : annulation de l'entretien\npar l'agent

REALISE --> [*]
ANNULE --> [*] 

@enduml