@startuml
!include ../skin.puml
title Diagramme d'activité du CU 3\n----


(*) --> "Liste des contacts prévus de son agence"
--> "Liste des agents de l'agence"
--> "Consulter détails agent"
--> "Liste des contacts d'un agent"
--> "Détails d'un contact (historique)"
--> (*)

@enduml