@startuml
!include ../skin.puml
title Diagramme d'activité du CU 3\n----


(*) --> "Consulter la liste des agents de l'agence"
--> "Consulter détails agent"
--> "Consulter les contacts d'un agent"
--> "Détails d'un contact"
--> (*)

@enduml