@startuml
!include ../skin.puml
title CU 10 - DACUCVVVCC \nConsultation du client\n----

(*) --> "Identifier le client"
--> Consulter le dossier\ndu client
"Consulter le dossier\ndu client" --> "MAJ entête dossier client"
"MAJ entête dossier client" --> (*)
"Consulter le dossier\ndu client" --> "Consulter Relations banque Client"
"Consulter Relations banque Client" --> (*)
"Consulter le dossier\ndu client" --> "Consulter Bilan Client \n(Cotation, bilan et liste\n de personnes)"
"Consulter Bilan Client \n(Cotation, bilan et liste\n de personnes)" --> "Consulter détails\nd'une personne"
"Consulter détails\nd'une personne" --> "MAJ Personne"
"MAJ Personne" --> (*)
"Consulter Bilan Client \n(Cotation, bilan et liste\n de personnes)" --> "Supprimer 1 personne"
"Supprimer 1 personne" --> (*)
"Consulter Bilan Client \n(Cotation, bilan et liste\n de personnes)" -> "Ajouter 1 personne"
if "Personne existane" then
  -->[oui] (*)
else
  -->[non] "Créer nouvelle personne"
  --> (*)
endif

"Consulter le dossier\ndu client" --> "Consulter Produits du\nclient à la banque\n et à la conurrence"
"Consulter Produits du\nclient à la banque\n et à la conurrence" --> "Consulter détail \nd'un compte"
"Consulter Produits du\nclient à la banque\n et à la conurrence" --> "MAJ Compte/Produit\nà la concurrence"
"Consulter Produits du\nclient à la banque\n et à la conurrence" --> "Consulter détail\nd'un produit"
"Consulter détail\nd'un produit" --> (*)
"MAJ Compte/Produit\nà la concurrence" --> (*)
"Consulter détail \nd'un compte" --> (*)
@enduml