@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 6\nPartie Client\n----

(*) --> "ListeContactClient"
--> "DetailsClient"
--> "VoirPlagesLibres"
--> "AssocierPlageEtContactSpontane"
--> "EditerLettreConfirmation"
--> (*)
@enduml