@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 6\nPartie Agent\n----

note left: ACTEUR_AGENT
(*) --> "ListeContatcsAgent"
--> "VoirDetailsContact"
--> "DossierClient"
note right: NoteDetailsClient
--> "VoirPlagesLibres"
note right: NotePropositionCreneau
--> "AssocierPlageEtContact"
--> "EditerLettreConfirmation"
--> (*)
@enduml