@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 6\nPartie Client\n----

note left: ACTEUR_AGENT
(*) --> "LB_RechercheClient"
--> "LB_DossierClientSpontane"
--> "LB_VoirPlagesLibres (CU 7)"
--> "LB_CreerContactSpontane"
--> "LB_CreerRDVSpontane"
--> "LB_EditerLettreConfirmation"
--> (*)
@enduml