@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 6\nPartie Client\n----

note left: ACTEUR_AGENT
(*) --> "RechercheClient"
--> "DossierClientSpontane"
--> "VoirPlagesLibres"
--> "CreerContactSpontane"
--> "CreerRDVSpontane"
--> "EditerLettreConfirmation"
--> (*)
@enduml