@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 6\nPartie Agent\n----

note left: ACTEUR_AGENT
(*) --> "LB_ListeContatcsAgent"
--> "LB_VoirDetailsContact"
--> "LB_DossierClient"
note right: NOTE_DetailsClient
--> "LB_VoirPlagesLibres"
note right: NOTE_PropositionCreneau
--> "LB_AssocierPlageEtContact"
--> "LB_EditerLettreConfirmation"
--> (*)
@enduml