@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 6\nPartie Agent\n----

note left: ACTEUR_AGENT
(*) --> "LB_ListeContatcsAgent"
--> "LB_DetailsContact (CU 4)"
--> "LB_DossierClient (CU 10)"
note right: NOTE_DetailsClient
--> "LB_VoirPlagesLibres (CU 7)"
note right: NOTE_PropositionCreneau
--> "LB_AssocierPlageEtContact"
--> "LB_EditerLettreConfirmation"
--> (*)
@enduml