@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité du CU 1\n----

note left: ACTEUR_SYS
(*)--> LB_ListeEvt
--> LB_TraiterEvt
--> LB_GenererMotif
--> LB_GenererContact

if "Tous les évènements\nont été traités ?" then
  -->[oui](*)
else
  -->[non]LB_TraiterEvt
endif

@enduml