@startuml
!include ../variables.puml
!include ../skin.puml

title Diagramme de séquence détaillé du CU 1\n----

"ACTEUR_STS" -> "ACTEUR_SI" : SM_GenererContacts

"ACTEUR_SI" -> Evenement : SOM_TraiterEvt
loop tant qu'il reste des événements à traiter
Evenement -> Contact : SOM_GenererContactPrevu
end



@enduml