@startuml
!include ../variables.puml
!include ../skin.puml

title Diagramme de séquence détaillé du CU 1\n----

actor "ACTEUR_STS"

"ACTEUR_STS" -> "ACTEUR_IHM" : Générer les contacts
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_GenererContacts
"ACTEUR_SI" -> Contact : SOM_GenererContacts

@enduml