'
' Acteurs
'
!define ACTEUR_SYS Déclenché par le\nsystème (horloge/timer)
!define ACTEUR_CHEF_AG Acteur : Le chef de l'agence
!define ACTEUR_AGENT Acteur : Un agent de l'agence

'
' CU1
'
!define ListeEvt Consulter la liste des évènements captés
!define TraiterEvt Traiter évènement
!define GenererMotif Générer un motif de contact
!define GenererContact Générer un contact prévu

' 
' CU2
'
!define ListeContacts Consulter la liste des contacts\n prévus de l'agence
!define DetailContact Consulter le détail d'un contact
!define DossierClient Consulter le dossier client du contact\n(CU10)
!define AffecterAgent Affecter le contact à l'agent sélectionné
!define NoteIncContact Mise à jour des indicateurs,\ndont un nouvel indicateur\ncorrespondant au nombre de\ncontacts affectés à l'agent
!define ListeAgents Consulter la liste des agents de l'agence
!define DetailAgent Consulter le détail d'un agent

'
' CU3
' CU2 -> !define ListeAgents
' CU2 -> !define DetailAgent
'
!define ContactsAgent Consulter les contacts d'un agent
!define DetailContact Détails d'un contact

'
' CU4
' CU2 !define DetailContact
'
!define ListeContactsATraiter Consulter la liste des contacts à traiter de l'agent
!define RegrouperContacts Regrouper les contacts\n(si même client)
!define RaisonAnnulation Enregistrer le motif d'annulation
!define AnnulerContact Annuler le contact
!define PrendreRDV Prendre RDV\n(CU 6)
!define PreparerRDV Preparer le RDV\n(CU 8)
!define ConduireRDV Conduire le RDV\n(CU 9)
!define NoteRegroupementContacts Définition d'un contact principal\net de contact(s) secondaire(s)

'
' CU7
'
!define ConsulterAgendaHebdoDeLAgent Consultation de l'agenda hebdomadaire de l'agent connecté
!define ConsulterAgendaQuotidien Consulter l'agenda quotidien\nde l'agence
!define ChangerAgent Changer d'agent
!define ChangerDate Changer de date
!define ChangerSemaine Changer de semaine
!define VoirDetailsRDV Consulter détails\nRDV
!define ModifierPlageHoraire Modifier plage\nhoraire
!define AnnulerRDV Annuler RDV
!define ReaffecterRDV Reaffecter RDV
!define ConsulterAgendaHebdomadaire Consulter l'agenda\n hebdomadaire d'un agent
!define VoirJourSuiv Voir jour\nsuivant
!define VoirJourPrec Voir jour\nprécédent


'
' Services Metier
'
!define SM_GenererContacts GenererContacts(void) : void
!define SM_ObtenirContactsPrevus ObtenirContactsPrevus(idStructure) : Liste <Contact>
!define SM_ObtenirDetailsContact ObtenirDetailsContact(idContact) \n: Details
!define SM_ObtenirDossierClient ObtenirDossierClient(idClient) : Client
!define SM_ObtenirAgents ObtenirAgents(idAgence) : Liste<Agent>
!define SM_ObtenirDetailsAgent ObtenirDetailsAgent(idAgent) \n: Details
!define SM_AffecterContact AffecterContact(idContact, idAgent) : void
!define SM_ObtenirContactsAgent ObtenirContactsAgent(idAgent) \n: Liste<Contact>
!define SM_ObtenirContactsAffecte ObtenirContactsAffectes(idAgent) : Liste<Contact>
!define SM_GrouperContacts GrouperContacts(Liste<idContact>) : void
!define SM_EnregistrerMotifAnnulation EnregistrerMotifAnnulation(motif) : void
!define SM_AnnulerContact AnnulerContact(idContact) : void
!define SM_PrendreRdv PrendreRdv(idContact) : void
!define SM_PreparerRdv PreparerRdv(idContact) : void
!define SM_ConduireRdv ConduireRdv(idContact) : void

'
' Acteurs DSS
'
!define ACTEUR_SI Système d'Information
!define ACTEUR_STS Tâches programmées\ndu système
!define ACTEUR_USER Utilisateur
!define ACTEUR_IHM Interface Utilisateur