''''''''''''''
' Acteurs CU '
''''''''''''''
!define ACTEUR_SYS Déclenché par le\nsystème (horloge/timer)
!define ACTEUR_CHEF_AG Acteur : Le chef de l'agence
!define ACTEUR_AGENT Acteur : Un agent de l'agence


'''''''''''''''
' Acteurs DSS '
'''''''''''''''
!define ACTEUR_SI SMA
!define ACTEUR_STS Tâches quotidienne\nsystème
!define ACTEUR_USER Agent
!define ACTEUR_CHEF Chef d'agence
!define ACTEUR_IHM IHM

'''''''''''''''' CU '''''''''''''''

'''''''
' CU1 '
'''''''
!define LB_ListeEvt Consulter la liste des évènements captés
!define LB_TraiterEvt Traiter évènement
!define LB_GenererMotif Générer un motif de contact
!define LB_GenererContact Générer un contact prévu

'''''''
' CU2 '
'''''''
!define LB_ListeContacts Consulter la liste des contacts\n prévus de l'agence
!define LB_DossierClient Consulter le dossier client du contact
!define LB_AffecterAgent Affecter le contact à l'agent sélectionné
!define NOTE_IncContact Mise à jour des indicateurs,\ndont un nouvel indicateur\ncorrespondant au nombre de\ncontacts affectés à l'agent
!define LB_ListeAgents Consulter la liste des agents de l'agence
!define LB_DetailAgent Consulter le détail d'un agent

'''''''
' CU3 '
'''''''
!define LB_ContactsAgent Consulter les contacts d'un agent

'''''''
' CU4 '
'''''''
!define LB_Ref_DetailContact Consulter le détail d'un contact\n(CU 4)
!define LB_DetailContact Consulter le détail d'un contact
!define LB_ListeContactsATraiter Consulter la liste des contacts à traiter de l'agent
!define LB_RegrouperContacts Regrouper les contacts\n(si même client)
!define LB_RaisonAnnulation Enregistrer le motif d'annulation
!define LB_AnnulerContact Annuler le contact
!define LB_PrendreRDV Prendre RDV\n(CU 6)
!define LB_PreparerRDV Preparer le RDV\n(CU 8)
!define LB_ConduireRDV Conduire le RDV\n(CU 9)
!define NOTE_RegroupementContacts Définition d'un contact principal\net de contact(s) secondaire(s)

'''''''
' CU5 '
'''''''
!define LB_ModePlanification Passer en mode planification
!define LB_SortirPlanification Valider et sortir du mode planification
!define LB_ConsulterAgenda Consulter l'agenda\n(CU 7)
!define LB_SelectPlage Sélectionner une plage\nhoraire libre
!define LB_CreerPlage Créer une plage agenda
!define LB_SelectActivite Sélectionner le type d'activité\nà plannifier
!define LB_MajNbContacts Mettre à jour le nombre de\ncontacts potentiels

'''''''
' CU6 '
'''''''
''' CU6 - Partie Agent
!define LB_ListeContatcsAgent Consulter la liste des contacts\nprévus de l'agent
!define LB_VoirPlagesLibres Voir les plages agenda libres
!define LB_AssocierPlageEtContact Créer un rendez-vous commercial
!define LB_EditerLettreConfirmation Editer la lettre\nde confirmation du rendez-vous
!define NOTE_DetailsClient Utilisation des informations\npour contacter le client
!define NOTE_PropositionCreneau Propositions de plusieurs\ncréneaux au client

''' CU6 - Partie Client
!define LB_RechercheClient Rechercher le client
!define LB_ListeContactClient Consuler la liste des contacts du client
!define LB_CreerContactSpontane Créer un nouveau contact
!define LB_DossierClientSpontane Consulter son dossier client\n(CU 10)
!define LB_CreerRDVSpontane Créer un rendez-vous spontané


'''''''
' CU7 '
'''''''
!define LB_ConsulterAgendaHebdoDeLAgent Consultation de l'agenda hebdomadaire de l'agent connecté
!define LB_ConsulterAgendaQuotidien Consulter l'agenda quotidien\nde l'agence
!define LB_ChangerAgent Changer d'agent
!define LB_ChangerDate Changer de date
!define LB_ChangerSemaine Changer de semaine
!define LB_VoirDetailsRDV Consulter détails RDV
!define LB_ModifierPlageHoraire Modifier plage horaire
!define LB_AnnulerRDV Annuler RDV
!define LB_ReaffecterRDV Reaffecter RDV
!define LB_ConsulterAgendaHebdomadaire Consulter l'agenda\n hebdomadaire d'un agent
!define LB_VoirJourSuiv Voir jour\nsuivant
!define LB_VoirJourPrec Voir jour\nprécédent
!define LB_ActionsAgenda Actions Agenda CU7

'''''''
' CU8 '
'''''''
!define LB_IdentifierContact Identifier le contact
!define LB_DetailsContact Voir les détails du contact
!define LB_ConsulterDossierClient Consulter le dossier du client
!define LB_MAJInfos Mettre à jour les informations
!define LB_EnregistrerCompteRenduDePreparation Enregistrer le compte rendu du préparation
!define LB_ListerOffres Consulter la liste des offres
!define LB_DetailsDesOffresCatalogue Voir le détails d'une offre du catalogue
!define LB_CreerPropositionOffre Créer une proposition commerciale
!define LB_EnregistrerCompteRenduDePreparation Enregistrer le compte rendu de préparation


'''''''
' CU9 '
'''''''
!define LB_AfficherPreparation Afficher les propositions commerciales\net annotations enregistrées
!define LB_EnregistrerRapportActiviteCommerciale Enregistrer le rapport\nd'activité commerciale
!define NOTE_ContactTermine Enregistrer le contact\ncomme étant terminé
!define LB_RedigerEtSoumettrePropositions Soumettre des propositions commerciales

''''''''
' CU10 '
''''''''
!define LB_IdentifierClient Identifier le client
!define LB_ConsulterBilanClient Consulter bilan client\n(cotation, liste de personnes)
!define LB_ConsulterDetailsPersonne Consulter details\nd'une personne
!define LB_MAJPersonne Mise à jour personne
!define LB_RecupererPersonne Récupérer personne
!define LB_AjouterPersonne Ajouter une personne
!define LB_CreerNouvellePersonne Créer nouvelle personne
!define LB_SupprPersonne Supprimer une personne
!define LB_ConsulerProduitsClient Consulter produits du\nclient à la banque\net à la concurrence
!define LB_ConsulterDetailsCompte Consulter détails\nd'un compte
!define LB_ConsulterDetailsProduit Consulter détail\n d'un produit
!define LB_MAJCompteConcurrence Maj compte/produit\nà la concurrence
!define LB_MAJCompteEnteteClient Maj entête client
!define LB_ConsulterRelationBanqueClient Consulter relations\n banque-client

'''''''''''''''' SERVICES '''''''''''''''

'''''''''''''''''''
' Saisies '
'''''''''''''''''''
!define SAISIE_SelectionnerContact Sélectionner un contact
!define SAISIE_SelectionnerPersonne Sélectionner une personne
!define SAISIE_SelectionnerContacts Sélectionner des contacts
!define SAISIE_SelectionnerAgent Sélectionner un agent
!define SAISIE_SelectionnerCompte Sélectionner un compte
!define SAISIE_MotifAnnulation Saisir le motif d'annulation
!define SAISIE_SelectionnerSemaine Sélectionner une semaine
!define SAISIE_SelectionnerRDV Sélectionner un rendez-vous
!define SAISIE_SelectionnerPlageHoraire Sélectionner une plage horaire
!define SAISIE_SelectionnerDate Sélectionner une date
!define SAISIE_SelectPlage Sélectionner une plage horaire libre
!define SAISIE_SelectActivite Sélectionner le type d'activité à planifier
!define SAISIE_EntrerInfosContact Saisir les informations du contact
!define SAISIE_SelectionnerClient Sélectionner un client
!define SAISIE_SaisirInfosClient Saisir les informations du client
!define SAISIE_SaisirInfosPersonne Saisir les informations de la personne
!define SAISIE_SaisirInfosCompte Saisir les infos concernant le compte
!define SAISIE_SelectionnerOffre Sélectionner une offre
!define SAISIE_RedigerProposition Rédiger une proposition d'offre
!define SAISIE_EcrireLettreConfirmation Ecrire lettre de confirmation de rendez-vous
!define SAISIE_InformationsContactSpontane Saisir les infos concernant le contact
!define SAISIE_InformationsRDVSpontane Saisir les informations concernant le rendez-vous
!define SAISIE_AnnotationsCRPreparation Saisir les annotations du compte-rendu de préparation
!define SAISIE_EnteteDossier Saisir les infos de l'entete du dossier
!define SAISIE_SelectionnerListeAgents Sélectionner les agents à afficher dans l'agenda
'''''''''''''''''''
' Services Metier '
'''''''''''''''''''
!define SM_GenererContacts GenererContacts(void)\n: void
!define SM_ObtenirContactsPrevus ObtenirContactsPrevus(idAgence)\n: Liste <Contact, PlageAgenda, Agent, Client>
!define SM_ObtenirDetailsContact ObtenirDetailsContact(idContact)\n: Contact, MotifDeContact, Client, Agent,\nListe<PropositionCommerciale, Offre, Liste<Produit>>
!define SM_ObtenirDossierClient ObtenirDossierClient(idClient)\n: Client
!define SM_ObtenirAgents ObtenirAgents(idAgence)\n: Liste<Agent>
!define SM_ObtenirDetailsAgent ObtenirDetailsAgent(idAgent) \n: agent, Liste<Contact>
!define SM_AffecterContact AffecterContact(idContact, idAgent)\n: void
!define SM_ObtenirContactsAgent ObtenirContactsAgent(idAgent)\n: Liste<Contact>
!define SM_ObtenirContactsAffectes ObtenirContactsATraiter(idAgent)\n: Liste <Contact, PlageAgenda, Agent, Client>
!define SM_GrouperContacts GrouperContacts(idContactPrincipal, Liste<idContactPrevus>)\n: void
!define SM_AnnulerContact AnnulerContact(idContact, motif)\n: void
!define SM_PrendreRdv PrendreRdv(idContact)\n: void
!define SM_PreparerRdv PreparerRdv(idContact)\n: void
!define SM_ConduireRdv ConduireRdv(idContact)\n: void
!define SM_ObtenirAgendaAgent ObtenirAgendaAgent(idAgent, numSemaine, annee)\n: Liste<PlageAgenda>, Liste<TacheElementaire>,\n  Liste<TypeActivite>
!define SM_ReaffecterRdv ReaffecterRdv(idPlageAgenda, idAgent)\n: void
!define SM_ObtenirDetailsRdv ObtenirDetailsRdv(idPlageAgenda)\n: PlageAgenda, Agent, Contact,\nMotifDeContact, Client
!define SM_ModifierPlageHoraire ModifierPlageHoraire(idPlageAgenda, datePlageHoraireDeb, datePlageHoraireFin) \n: PlageAgenda
!define SM_ObtenirAgendaQuotidien ObtenirAgendaAgence(idAgence, dateJour, Liste<Agent>)\n: Liste<PlageAgenda>, Liste<TacheElementaire>,\n  Liste<TypeActivite>
!define SM_AnnulerRdv AnnulerRdv(idPlageAgenda)\n: void
!define SM_CreerPlageAgenda CreerPlageAgenda(idAgent, idActivite, datePlageHoraireDeb, datePlageHoraireFin)\n: PlageAgenda
!define SM_MettreAJourNbContactsPotentiels MajNbContactsPotentiels(idAgent, Liste<idPlageAgenda>)\n: void
!define SM_IdentifierContact IdentifierContact(idContact)\n: Contact
!define SM_MAJInfos MAJInfos(saisie, idClient)\n: void
!define SM_ObtenirOffres ObtenirOffres(void)\n: Liste<Offre>
!define SM_ObtenirDetailsOffre ObtenirDetailsOffre(idOffre)\n: Liste<Produit>, commentairesOffre
!define SM_AjouterPropositionCommerciale AjouterPropositionCommerciale(idOffre, idContact)\n: void
!define SM_EnregistrerCompteRendu EnregistrerCompteRenduPreparation(annotations, idContact)\n: void
!define SM_ObtenirPropositionCommerciale ObtenirPropositionCommerciale(idContact)\n: Liste<PropositionCommerciale>, annotations
!define SM_EnregistrerRapportActivite EnregistrerRapportActivite(idContact)\n: void
!define SM_ConsulterDossierClient ConsulterDossierClient(idClient)\n: numero, denomination, adresse postale
!define SM_ConsulterBilanClient ConsulterBilanClient(idClient)\n: cotationsClient, Liste<Personne>
!define SM_ConsulterDetailsPersonne ConsulterDetailPersonne(idPersonne)\n: adresse, revenu, impot, dateNaissance, Liste<Client>
!define SM_MAJPersonne MettreAJourPersonne(idPersonne, nom, prenom,\nadresse, revenu, impot, dateNaissance)\n: void
!define SM_RecupererPersonne RecupererPersonne(nom, prenom, trancheAge, adresse)\n: Personne
!define SM_AjouterPersonne AjouterPersonne(idClient, nom, prenom,\ndateNaissance, adresse, revenus, impots)\n: void
!define SM_CreerEtAjouterNouvellePersonne CreerEtAjouterNouvellePersonne(idClient, nom, prenom,\ndateNaissance, adresse, revenus, impots)\n: void
!define SM_SupprimerPersonne SupprimerPersonne(idClient, idPersonne)\n: void
!define SM_MAJEnteteDossier MAJEnteteDossier\n(idClient, denomination, adressePostale)\n: void
!define SM_ObtenirProduits ObtenirProduits(idClient)\n: Liste<Compte, Produit>
!define SM_ObtenirDetailCompte ObtenirDetailCompte(idCompte)\n: details, historique
!define SM_ObtenirDetailProduit ObtenirDetailProduit(idProduit)\n: solde, découvert, interet...
!define SM_MAJComptesConcurrence MAJComptesConcurrence(idClient, txtComptesConcurrence)\n: void 
!define SM_VoirPlagesLibres ObtenirPlagesLibres(idAgent)\n: Liste<PlageAgenda>
!define SM_AssocierPlageEtContact AffecterContactAUnePlage(idPlage, idContact)\n: void
!define SM_EditerLettreConfirmation EnregistrerLettreConfirmationRdv(idContact, texteLettre)\n: void
!define SM_RechercherClient RechercherClient(prenom, nom, etc)\n: client
!define SM_CreerContactSpontane CreerContactSpontane(idClient, idAgent, motifContact)\n: contactPrevu, contactRealise
!define SM_CreerRDVSpontane CreerRDVSpontane(idContactRealise, date, commentaire)\n: plageAgenda
!define SM_ConsulterRelationsBanqueClient ConsulterRelationsBanqueClient(idClient)\n: technique de contact, incidents, reclamations,\nListe<PropositionCommerciale>, Liste<Contact>, Liste<Evenement> 
!define SM_ObtenirListeAgence ObtenirListeAgence(void)\n: Liste<Agence>
!define SM_ObtenirClientContact ObtenirClientDuContact(idContact) : Client
!define SM_IdentifierContactAvecInfos IdentifierContact(denomination, nomClient, etc.)\n: Contact
!define SM_ObtenirClientEtAgence ObtenirClientEtAgence(idClient)\n: Client, Agence
!define SM_ObtenirContactsAgent ObtenirContactsAgent(idAgent)\n: Liste<Client, Contact, PlageAgenda>


'''''''''''''''''''''''''
' Services Objet Metier '
'''''''''''''''''''''''''

' SOM Personne
!define SOM_ObtenirPersonne ObtenirPersonne(idPersonne)\n: Personne
!define SOM_MAJPersonne MAJPersonne(idPersonne, nom, prenom,\nadresse, revenu, impot, dateNaissance)\n: void
!define SOM_TrouverPersonne TrouverPersonne(nom, prenom, trancheAge, adresse)\n: Personne
!define SOM_CreerPersonne CreerPersonne(nom, prenom,\ndateNaissance, adresse, revenus, impots)\n: Personne
!define SOM_ObtenirDetailsPersonne ObtenirDetailsPersonne(idPersonne)\n: adresse, revenu, impot, dateNaissance

' SOM Client
!define SOM_ObtenirClientsStructure ObtenirClientsAgence(idAgence)\n: Liste<Client>
!define SOM_ObtenirClient ObtenirClient(idClient)\n: Client
!define SOM_ConsulterBilanClient ConsulterDetailClient(idClient)\n: cotationsClient, Liste<idPersonne>
!define SOM_AjouterPersonne AjouterPersonne(idClient, idPersonne)\n: void
!define SOM_SupprimerPersonne SupprimerPersonne(idClient, idPersonne)\n: void
!define SOM_MajEnteteDossier MajEnteteDossier(idClient, denomination, adressePostale)\n: void
!define SOM_ObtenirProduits ObtenirProduits(idClient)\n: Liste<Compte, idProduit>
!define SOM_ObtenirCompte ObtenirDetailsCompte(idCompte)\n: details, historique
!define SOM_MAJComptesConcurrence MajComptesConcurrence(idClient, txtComptesConcurrence)\n: void
!define SOM_RechercherClient RechercherClient(prenom, nom, etc.)\n: client
!define SOM_ConsulterInfosRelationClient ConsulterInfosRelationClient(idClient)\n: technique de contact, incidents, réclamations
!define SOM_ObtenirClientAvecInfos ObtenirClientAvecInfos(nom, prenom, denomination) : Client
!define SOM_ObtenirClientContact ObtenirClientDuContact(idContact) : Client
!define SOM_MAJInfos MAJInfos(saisie, idClient)\n: void
!define SOM_ObtenirClientsDeLaPersonne ObtenirClientsPersonne(idPersonne)\n: Liste<Client>

' SOM Contact
!define SOM_ObtenirContactsPrevus ObtenirContactsPrevus(idClient)\n: Liste<Contact>
!define SOM_ObtenirContactsAgence ObtenirContactsAgence(idAgence)\n: Liste<Contact, idAgent, idPlageAgenda, idClient>
!define SOM_ObtenirPlageAgenda ObtenirPlageAgenda(idPlageAgenda)\n: PlageAgenda
!define SOM_ObtenirDetailsContact ObtenirDetailsContact(idContact)\n: Contact, MotifDeContact, idClient, idAgent,\nListe<PropositionCommerciale, idOffre>
!define SOM_ObtenirContactsAgent ObtenirContactsAgent(idAgent)\n: Liste<Contact>
!define SOM_AnnulerRdvContact AnnulerRdv(idPlageAgenda)\n: void
!define SOM_CreerContactSpontane CreerContactSpontane(idClient, idAgent, motifContact)\n: contactPrevu, contactRealise
!define SOM_EditerLettreConfirmation EnregistrerLettreConfirmationRdv(idContact, texteLettre)\n: void
!define SOM_ConsulterPropositionsHistorique ConsulterPropositionsHistorique(idClient)\n: Liste<PropositionCommerciale>, Liste<Contact>
!define SOM_EnregistrerCompteRendu EnregistrerCompteRenduPreparation(annotations, idContact)\n: void
!define SOM_IdentifierContact IdentifierContact(denomination, nomClient, etc.)\n: Contact
!define SOM_AjouterPropositionCommerciale AjouterPropositionCommerciale(idContact, idOffre)\n: void
!define SOM_ObtenirPropositionCommerciale ObtenirPropositionCommerciale(idContact)\n: PropositionCommerciale, annotations
!define SOM_EnregistrerRapportActivite EnregistrerRapportActivite(idContact)\n: void

' SOM Produit
!define SOM_DetailOffre ObtenirDetailOffre(idOffre)\n: Offre, Liste<Produit>
!define SOM_ObtenirProduit ObtenirProduit(idProduit)\n: Produit
!define SOM_ObtenirOffres ObtenirOffres(void)\n: Liste<Offre>
!define SOM_ObtenirDetailsProduit ObtenirDetailsProduit(idProduit)\n: solde, découvert, interet...

' SOM Structure
!define SOM_ObtenirAgentsStructure ObtenirAgents(idAgence)\n: Liste<Agent>
!define SOM_ObtenirAgent ObtenirAgent(idAgent)\n: Agent
!define SOM_MettreAJourNbContactsPotentiels MajNbContactsPotentiels(idAgent, Liste<idPlageAgenda>)\n: void
!define SOM_ObtenirAgenceId ObtenirAgenceId(nom)\n: agenceId
!define SOM_MettreAJourNbContactsAffectes MettreAJourNbContactsAffectes(idAgent)\n: void
!define SOM_ObtenirDetailsOffre ObtenirDetailsOffre(idOffre)\n: Liste<Produit>, commentairesOffre
!define SOM_ObtenirAgenceDuClient ObtenirAgenceDuClient(idClient)\n: Structure

' SOM Agenda
!define SOM_CreerPlageAgenda CreerPlageAgenda(idAgent, idActivite, datePlageHoraireDeb, datePlageHoraireFin)\n: PlageAgenda
!define SOM_DetailPlageAgenda DetailPlageAgenda(idPlageAgenda)\n: plageAgenda
!define SOM_ObtenirAgendaAgent ObtenirAgendaAgent(idAgent, numSemaine, annee)\n: Liste<PlageAgenda>, Liste<TacheElementaire,\n  Liste<TypeActivite>
!define SOM_ObtenirAgendaQuotidien ObtenirAgendaAgence(idAgence, dateJour, Liste<Agent>)\n: Liste<PlageAgenda>, Liste<TacheElementaire>,\n  Liste<TypeActivite>
!define SOM_ReaffecterRdv ReaffecterRdv(idPlageAgenda, idAgent)\n: void
!define SOM_ObtenirDetailsRdv ObtenirDetailsRdv(idPlageAgenda)\n: PlageAgenda, idAgent, idContact, idClient
!define SOM_ModifierPlageHoraire ModifierPlageHoraire(idPlageAgenda, datePlageHoraireDeb, datePlageHoraireFin)\n: PlageAgenda
!define SOM_AnnulerRdv AnnulerRdv(idPlageAgenda)\n: void
!define SOM_VoirPlagesLibres ObtenirPlagesLibres(idAgent)\n: Liste<PlageAgenda>
!define SOM_CreerRDVSpontane CreerRDVSpontane(idContactRealise, date, commentaire)\n: PlageAgenda
!define SOM_TraiterEvt RecupererEvenementsATraiter()\n: Liste<Evenement, idClient>
!define SOM_GenererMotif GenererMotifContact(idEvenement)\n: motif
!define SOM_GenererContactPrevu GenererContactPrevu(idClient, idEvenement)\n: void
!define SOM_ObtenirDossierClient ObtenirDossierClient(idClient)\n: motif, etat, etc.
!define SOM_ObtenirDetailsAgent ObtenirDetailsAgent(idAgent)\n: agent, Liste<ContactPrevu>
!define SOM_AffecterContact AffecterContact(idContact, idAgent)\n: void
!define SOM_ObtenirContactsAffectes ObtenirContactsATraiter(idAgent)\n: Liste<Contact>
!define SOM_GrouperContacts GrouperContacts(idContactPrincipal, Liste<idContactPrevus>)\n: void
!define SOM_AnnulerContact AnnulerContact(idContact, motif)\n: void
!define SOM_PrendreRdv PrendreRdv(idContact)\n: void
!define SOM_PreparerRdv PreparerRdv(idContact)\n: void
!define SOM_ConduireRdv ConduireRdv(idContact)\n: void
!define SOM_ReaffecterRdv ReaffecterRdv(idPlageAgenda, idAgent)\n: void
!define SOM_VoirPlagesLibres ObtenirPlagesLibres(idAgent) : Liste<PlageAgenda>
!define SOM_AssocierPlageContact AffecterContactAUnePlage(idPlageAgenda, idContact) : void
!define SOM_ObtenirDateRdv ObtenirDateRdv(idContact) : PlageAgenda

' SOM Evenement
!define SOM_ConsulterEvenementsAVenir ConsulterEvenementsAVenir(idClient)\n: Liste<Evenement>

''''''''''
'  EdF   '
''''''''''

!define V_LoginPage Page d'authentification
!define V_OngletClient Onglet Client
!define V_ResultatRecherche Resultat recherche client
!define V_BilanDossierClient Onglet Bilan dossier client
!define V_ProduitClient Onglet Produit
!define V_RelationsClient Onglet Relations
!define V_OngletAgenda Onglet Agenda
!define V_OngletAgendaAgence Vue Agence
!define V_OngletAgendaAgent Vue Agent
!define V_PopupAjoutActivite Popup d'ajout d'activite
!define V_PopupAjoutContactCommercial Popup d'ajout d'un contact commercial
!define V_PopupAjoutContactSpontane Popup d'ajout d'un contact spontane
!define V_PopupChoixContact Popup de selection d'un contact
!define V_PopupChoixClient Popup de selection d'un client
!define V_PopupAjoutTache Popup d'ajout d'une tâche
!define V_PopupConsultationTache Popup de consultation d'une tache
!define V_OngletPersonnes Onglet Personnes
!define V_OngletContacts Onglet Contacts
!define V_DossierEditable Dossier Editable 
!define V_DossierNonEditable Dossier Non Editable
!define V_ModeConsultation Mode Consultation
!define V_ModePlanification Mode Planification
!define V_VueContacts Liste des contacts
!define V_VueContact Vue Contact
!define V_ContactOngletPreparation Onglet preparation 
!define V_ContactOngletCR Onglet compte-rendu 
!define V_PopupAffecterContact Popup d'affectation d'un agent au contact
!define V_PopupAjouterOffre Popup d'ajout d'une offre
!define V_VuePersonnes Liste des personnes
!define V_VuePersonne Vue donnant les détails d'une personne 
!define V_DetailsProduit Vue donnant les détails d'un prooduit
!define V_PersonneEditable Mode personne editable
!define V_PersonneConsultable Mode personne consultable
!define V_GestionPersonnes Vue de gestion des personnes
!define V_CreerPersonne Vue de creation d'une personne
!define V_PopupConsultationRDV Popup de consultation d'un rendez-vous
!define V_PopupAnnulationContact Popup motif annulation contact 