@startuml
!include ../skin.puml
!include ../variables.puml


state "V_LoginPage" as S_LoginPage

[*] --> S_LoginPage

state "Application" as application {

  state "V_OngletClient" as S_OngletClient {
      state "V_DossierEditable" as S_DossierEditable
      state "V_DossierNonEditable" as S_DossierNonEditable

      [*] -right-> S_DossierNonEditable
      S_DossierEditable --left--> S_DossierNonEditable
      S_DossierNonEditable --> S_DossierEditable

      --
      state "V_ResultatRecherche" as S_ResultatRecherche
      state "V_BilanDossierClient" as S_BilanDossierClient
      state "V_ProduitClient" as S_ProduitClient
      state "V_RelationsClient" as S_RelationsClient
      state "V_DetailsProduit" as S_DetailsProduit

      [*] --> S_ResultatRecherche
      S_ResultatRecherche --> S_BilanDossierClient
      S_BilanDossierClient -left-> S_ProduitClient
      S_BilanDossierClient -right-> S_RelationsClient
      S_ProduitClient --> S_BilanDossierClient
      S_ProduitClient --> S_RelationsClient
      S_RelationsClient --> S_ProduitClient
      S_RelationsClient --> S_BilanDossierClient

      S_ProduitClient --> S_DetailsProduit
      S_DetailsProduit --> S_ProduitClient
  }

  state "V_OngletAgenda" as S_OngletAgenda {
      state "V_ModeConsultation" as S_ModeConsultation
      state "V_ModePlanification" as S_ModePlanification

      [*] -left-> S_ModeConsultation
      S_ModeConsultation --left--> S_ModePlanification
      S_ModePlanification --> S_ModeConsultation

      --

      [*] --> S_OngletAgendaAgent
      state "V_OngletAgendaAgence" as S_OngletAgendaAgence
      state "V_OngletAgendaAgent" as S_OngletAgendaAgent
      state "V_PopupConsultationTache" as S_PopupConsultationTache
      state "V_PopupAjoutActivite" as S_PopupAjoutActivite
      state "V_PopupAjoutContactCommercial" as S_PopupAjoutContactCommercial
      state "V_PopupAjoutContactSpontane" as S_PopupAjoutContactSpontane
      state "V_PopupChoixContact" as S_PopupChoixContact
      state "V_PopupChoixClient" as S_PopupChoixClient
      state "V_PopupAjoutTache" as S_PopupAjoutTache
      state "V_PopupConsultationRDV" as S_PopupConsultationRDV

      S_OngletAgendaAgence -left--> S_OngletAgendaAgent
      S_OngletAgendaAgent ---> S_OngletAgendaAgence

      S_OngletAgendaAgence ---> S_PopupAjoutActivite : [V_ModePlanification]
      S_PopupAjoutActivite --> S_OngletAgendaAgence
      S_OngletAgendaAgent ---> S_PopupAjoutActivite : [V_ModePlanification]
      S_PopupAjoutActivite --> S_OngletAgendaAgent
      S_OngletAgendaAgence ---> S_PopupAjoutTache : [V_ModePlanification]
      S_PopupAjoutTache --> S_OngletAgendaAgence

      S_OngletAgendaAgent -up--> S_PopupConsultationTache
      S_PopupConsultationTache --> S_OngletAgendaAgent
      S_OngletAgendaAgence --> S_PopupConsultationTache
      S_PopupConsultationTache --> S_OngletAgendaAgence

      S_OngletAgendaAgent -up--> S_PopupConsultationRDV
      S_PopupConsultationRDV --> S_OngletAgendaAgent
      S_OngletAgendaAgence --> S_PopupConsultationRDV
      S_PopupConsultationRDV --> S_OngletAgendaAgence

      S_PopupAjoutActivite --> S_PopupAjoutContactCommercial
      S_PopupAjoutContactCommercial --> S_PopupAjoutActivite

      S_PopupAjoutActivite --> S_PopupAjoutContactSpontane
      S_PopupAjoutContactSpontane --> S_PopupAjoutActivite

      S_PopupAjoutContactCommercial --> S_PopupChoixContact
      S_PopupChoixContact --> S_PopupAjoutContactCommercial

      S_PopupAjoutContactSpontane --> S_PopupChoixClient
      S_PopupChoixClient --> S_PopupAjoutContactSpontane

  }

  state "V_OngletPersonnes" as S_OngletPersonnes {
      state "V_PersonneConsultable" as S_PersonneConsultable
      state "V_PersonneEditable" as S_PersonneEditable
      
      [*] -left-> S_PersonneConsultable
      S_PersonneConsultable -left-> S_PersonneEditable
      S_PersonneEditable --> S_PersonneConsultable
      
      --
      state "V_GestionPersonnes" as S_GestionPersonnes
      state "V_CreerPersonne" as S_CreerPersonne
      state "V_VuePersonnes" as S_VuePersonnes
      state "V_VuePersonne" as S_VuePersonne

      [*] --> S_GestionPersonnes
      S_GestionPersonnes --> S_VuePersonnes
      S_VuePersonnes --> S_GestionPersonnes
      S_GestionPersonnes --> S_CreerPersonne
      S_CreerPersonne --> S_GestionPersonnes
      S_VuePersonnes --> S_VuePersonne
      S_VuePersonne --> S_VuePersonnes
  }

  state "V_OngletContacts" as S_OngletContacts {
      state "V_VueContacts" as S_VueContacts
      state "V_PopupAnnulationContact" as S_PopupAnnulationContact
      state "V_PopupAffecterContact" as S_PopupAffecterContact
      
      state "V_VueContact" as S_VueContact {
          state "V_ContactOngletPreparation" as S_ContactOngletPreparation
          state "V_ContactOngletCR" as S_ContactOngletCR
          state "V_PopupAjouterOffre" as S_PopupAjouterOffre


          [*] -left-> S_ContactOngletPreparation 
          S_ContactOngletPreparation -left-> S_ContactOngletCR
          S_ContactOngletCR --> S_ContactOngletPreparation

          S_ContactOngletPreparation --> S_PopupAjouterOffre
          S_PopupAjouterOffre --> S_ContactOngletPreparation
      }

      [*] --> S_VueContacts
      S_VueContacts -down-> S_VueContact
      S_VueContact --> S_VueContacts
      S_VueContacts -left-> S_PopupAnnulationContact
      S_PopupAnnulationContact --> S_VueContacts
      S_VueContacts -right-> S_PopupAffecterContact
      S_PopupAffecterContact --> S_VueContacts

  }

  S_LoginPage -right-> S_OngletAgenda
  S_OngletClient --> S_OngletAgenda
  S_OngletClient --> S_OngletPersonnes
  S_OngletClient --> S_OngletContacts
  S_OngletAgenda -right-> S_OngletClient
  S_OngletAgenda --> S_OngletPersonnes
  S_OngletAgenda --> S_OngletContacts
  S_OngletPersonnes --> S_OngletClient
  S_OngletPersonnes --> S_OngletAgenda
  S_OngletPersonnes -right-> S_OngletContacts
  S_OngletContacts --> S_OngletClient
  S_OngletContacts --> S_OngletAgenda
  S_OngletContacts --> S_OngletPersonnes

}

application -left-> [*]

@enduml