@startuml
!include ../skin.puml
title Diagramme de séquence système du CU 1\n----

actor User

User -> IHM : Consulter liste des événements
IHM -> Système : RecupererEvenements() \n: Liste <Evenements>
loop il reste des événements
User -> IHM : Consulter un événement
IHM -> Système : GenererContact(idEvenement, idClient)\n: Contact
end


@enduml