@startuml
!include ../skin.puml
title Diagramme d'activité du CU 1\n----


(*) --> "Lister les évènements captés"
--> "Traiter évènement"
"Traiter évènement" --> "Générer un motif de contact"
"Générer un motif de contact" --> "Générer un contact prévu"

if "Tous les évènements\nont été traités ?" then
  -->[oui] (*)
else
  -->[non] "Traiter évènement"
endif

@enduml