@startuml
!include ../skin.puml
title Diagramme d'activité du CU 1\n----


(*) --> "Liste des évènements captés"
--> "Consulter évènement"
"Consulter évènement" --> "Générer un motif de contact"
"Générer un motif de contact" --> "Générer un contact prévu"

if "Tous les évènements\nont été traités ?" then
  -->[oui] (*)
else
  -->[non] "Consulter évènement"
endif

@enduml