@startuml
!include ../skin.puml
title Diagramme d'activité du CU 5\n----


(*) --> "Lister les agents" as ListeAgents
ListeAgents --> "Sélectionner un agent" as SelectAgent
SelectAgent --> "Lister les plages horaires" as ListePlages
ListePlages --> "Sélectionner une plage\nhoraire libre" as SelectPlage
SelectPlage --> "Lister les activités" as ListeActivites
ListeActivites --> "Sélectionner le type d'activité\nà plannifier" as SelectActivite

if "encore des activités\nà plannifier"
    --> [oui] ListePlages
else
    --> "Mettre à jour le nombre de\ncontacts potentiels" as MajNbContacts
endif

MajNbContacts --> (*)

@enduml