@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité\ndu CU 8\n----

note left: ACTEUR_AGENT
(*) --> "IdentifierContact"
--> "DetailsContact"
--> "DossierClient"
--> ===B1===
--> "MAJInfos"
--> ===B2===
===B1=== --> "ListerOffres"
--> "DetailsDesOffresCatalogue"
--> "CreerPropositionOffre"
--> ===B2===
--> "EnregistrerCompteRenduDePreparation"
--> (*)
@enduml