@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité\ndu CU 8\n----

note left: ACTEUR_AGENT
(*) --> "IdentifierContact"
--> "DetailsContact"
--> "DossierClient"
--> "MAJInfos"
--> "EnregistrerCompteRenduDePreparation"
"DossierClient" --> "ListerOffres"
--> "DetailsDesOffresCatalogue"
--> "CreerPropositionOffre"
--> "EnregistrerCompteRenduDePreparation"
--> (*)
@enduml