@startuml
!include ../skin.puml
!include ../variables.puml
title Diagramme d'activité\ndu CU 8\n----

(*) --> "ListeClient"
--> "DetailsClient"
--> "ListeContacts"
--> "DetailsContact"
--> "ConsulterDossierClient"
--> "MAJInfos"
--> "EnregistrerCompteRenduDePreparation"
"ConsulterDossierClient" --> "ListerOffres"
--> "DetailsDesOffresCatalogue"
--> "EnregistrerCompteRenduDePreparation"
--> (*)
@enduml