@startuml
!include ../skin.puml
!include ../variables.puml

title Diagramme de séquence système du CU 8\n----

actor "ACTEUR_USER"

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_IdentifierContact
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_IdentifierContact
"ACTEUR_SI" -> "Contact" : SOM_IdentifierContact

"ACTEUR_USER" -> "ACTEUR_IHM" : LB_Ref_DetailContact

alt Mise à jour client
	"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerClient
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ConsulterDossierClient (CU 10)
	"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SaisirInfosClient
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_MAJInfos
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_MAJInfos
	"ACTEUR_SI" -> "Client" : SOM_MAJInfos
	
else Proposition commerciale
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_ListerOffres
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirOffres
	"ACTEUR_SI" -> "Produit" : SOM_ObtenirOffres
	
	"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_SelectionnerOffre
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_DetailsDesOffresCatalogue
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_ObtenirDetailsOffre
	"ACTEUR_SI" -> "Produit" : SOM_ObtenirDetailsOffre
	
	"ACTEUR_USER" -> "ACTEUR_IHM" : LB_CreerPropositionOffre
	"ACTEUR_IHM" -> "ACTEUR_SI" : SM_AjouterPropositionCommerciale
	"ACTEUR_SI" -> "Contact" : SOM_AjouterPropositionCommerciale

	ACTEUR_USER -> ACTEUR_IHM : SAISIE_RedigerProposition
	ACTEUR_USER -> ACTEUR_IHM : LB_AnnoterProposition
	ACTEUR_IHM -> ACTEUR_SI : SM_AnnoterProposition
	ACTEUR_SI -> Contact : SOM_AnnoterProposition
	
end

"ACTEUR_USER" -> "ACTEUR_IHM" : SAISIE_AnnotationsCRPreparation
"ACTEUR_USER" -> "ACTEUR_IHM" : LB_EnregistrerCompteRenduDePreparation
"ACTEUR_IHM" -> "ACTEUR_SI" : SM_EnregistrerCompteRendu
"ACTEUR_SI" -> "Contact" : SOM_EnregistrerCompteRendu


@enduml